server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/Allqu-Michi/backend-allqu-michi
          search-paths: config-data
  application:
    name: config-service